ERFs:
- atmabs
- LWCloudEff
- ERFtcsaf
- SWCloudEff
- ERFtlw
- SWDirectEff
- LWDirectEff
- atmabsSW
- DirectEff
- ERFtsw
- CloudEff
- ERFsurf
- ERFt
derived_vars:
- concoa
- cdncvi
- concso4
- concdust
vars:
- rsds
- abs550aer
- rsdscs
- sfcWind
- clt
- clivi
- depdust
- evspsbl
- clwvi
- od440aer
- od550aer
- emidust
- pr
- od870aer
- prc
