ERFs:
- SWDirectEff
- LWCloudEff
- DirectEff
- LWDirectEff
- SWCloudEff
- ERFtsw
- ERFtlw
- atmabs
- CloudEff
- atmabsSW
- ERFtcsaf
- ERFsurf
- ERFt
derived_vars:
- concso4
- concoa
- cdncvi
- concdust
vars:
- clt
- od440aer
- od550aer
- sfcWind
- evspsbl
- depdust
- emidust
- od870aer
- rsdscs
- rsds
- prc
- abs550aer
- clwvi
- clivi
- pr
