ERFs:
- LWCloudEff
- SWDirectEff
- LWDirectEff
- DirectEff
- atmabsSW
- SWCloudEff
- atmabs
- ERFtlw
- ERFtsw
- ERFsurf
- CloudEff
- ERFtcsaf
- ERFt
derived_vars:
- concso4
- cdncvi
- concoa
- conch2oaer
- concdust
vars:
- evspsbl
- pr
- od870aer
- od440aer
- sfcWind
- rsdscs
- clwvi
- clt
- rsds
- clivi
- od550aer
- prc
- abs550aer
- emidust
