ERFs:
- DirectEff
- atmabs
- ERFtsw
- ERFsurf
- SWDirectEff
- LWDirectEff
- atmabsSW
- ERFt
- LWCloudEff
- CloudEff
- ERFtlw
- SWCloudEff
- ERFtcsaf
derived_vars:
- cdncvi
- concdust
- conch2oaer
- concoa
- concso4
vars:
- sfcWind
- clivi
- clt
- pr
- clwvi
- od440aer
- rsds
- rsdscs
- evspsbl
- abs550aer
- prc
- od870aer
- od550aer
- emidust
