ERFs:
- DirectEff
- SWDirectEff
- atmabs
- SWCloudEff
- CloudEff
- LWDirectEff
- atmabsSW
- LWCloudEff
- ERFtlw
- ERFsurf
- ERFtcsaf
- ERFtsw
- ERFt
derived_vars:
- conch2oaer
- concoa
- concdust
- concso4
- cdncvi
vars:
- rsds
- clt
- pr
- abs550aer
- od550aer
- evspsbl
- clivi
- od440aer
- od870aer
- sfcWind
- prc
- emidust
- clwvi
- rsdscs
