ERFs:
- atmabs
- ERFtcsaf
- CloudEff
- SWDirectEff
- ERFtsw
- SWCloudEff
- LWCloudEff
- atmabsSW
- ERFtlw
- DirectEff
- ERFsurf
- LWDirectEff
- ERFt
derived_vars:
- concoa
- conch2oaer
- concdust
- concso4
- cdncvi
vars:
- od550aer
- pr
- clivi
- evspsbl
- prc
- clt
- abs550aer
- emidust
- od870aer
- rsds
- rsdscs
- od440aer
- sfcWind
- clwvi
