ERFs:
- atmabs
- LWCloudEff
- DirectEff
- SWCloudEff
- atmabsSW
- ERFtlw
- ERFtcsaf
- LWDirectEff
- CloudEff
- SWDirectEff
- ERFt
- ERFsurf
- ERFtsw
derived_vars:
- concso4
- conch2oaer
- concdust
- concoa
vars:
- prc
- abs550aer
- emidust
- pr
- evspsbl
- od550aer
- clwvi
- clt
- od440aer
- sfcWind
- rsdscs
- clivi
- rsds
