ERFs:
- ERFtsw
- ERFt
- atmabs
- ERFtlw
- SWDirectEff
- LWDirectEff
- atmabsSW
- LWCloudEff
- DirectEff
- ERFtcsaf
- CloudEff
- ERFsurf
- SWCloudEff
derived_vars:
- concoa
- concdust
- concso4
- cdncvi
- conch2oaer
vars:
- pr
- evspsbl
- od440aer
- od870aer
- clt
- rsdscs
- clwvi
- clivi
- emidust
- abs550aer
- prc
- rsds
- od550aer
- sfcWind
