ERFs:
- ERFtsw
- ERFtlw
- atmabsSW
- atmabs
- ERFsurf
- ERFt
derived_vars:
- concso4
- cdncvi
- concdust
- concoa
vars:
- rsds
- prc
- rsdscs
- emidust
- clwvi
- od870aer
- abs550aer
- od550aer
- sfcWind
- pr
- clivi
- evspsbl
- clt
