ERFs:
- ERFtlw
- ERFsurf
- ERFt
- ERFtsw
- atmabs
- atmabsSW
derived_vars:
- concso4
- concdust
- concoa
- cdncvi
vars:
- od440aer
- clt
- clivi
- clwvi
- prc
- rsds
- evspsbl
- sfcWind
- pr
- rsdscs
- emidust
- od550aer
- abs550aer
- od870aer
