ERFs:
- atmabs
- atmabsSW
- ERFt
- ERFtlw
- ERFsurf
- ERFtsw
derived_vars:
- concso4
- cdncvi
- concoa
- concdust
vars:
- prc
- emidust
- rsdscs
- pr
- od550aer
- clivi
- od870aer
- sfcWind
- clt
- evspsbl
- clwvi
- rsds
- abs550aer
