ERFs:
- atmabs
- SWDirectEff
- ERFt
- DirectEff
- SWCloudEff
- ERFtlw
- LWDirectEff
- ERFtsw
- ERFsurf
- ERFtcsaf
- CloudEff
- atmabsSW
- LWCloudEff
derived_vars:
- cdncvi
- concoa
- concdust
- concso4
- conch2oaer
vars:
- sfcWind
- emidust
- pr
- rsds
- clivi
- od550aer
- od870aer
- rsdscs
- evspsbl
- od440aer
- clt
- abs550aer
- clwvi
- prc
