ERFs:
- atmabsSW
- ERFsurf
- SWDirectEff
- CloudEff
- LWDirectEff
- ERFtcsaf
- DirectEff
- ERFt
- ERFtlw
- LWCloudEff
- ERFtsw
- SWCloudEff
- atmabs
derived_vars:
- concoa
- cdncvi
- concso4
- concdust
vars:
- clwvi
- rsds
- od440aer
- clt
- pr
- abs550aer
- prc
- od870aer
- od550aer
- evspsbl
- rsdscs
- clivi
- sfcWind
- emidust
