ERFs:
- atmabsSW
- atmabs
- ERFtlw
- ERFt
- ERFtsw
- ERFsurf
derived_vars:
- concso4
- concoa
- conch2oaer
- concdust
- cdncvi
vars:
- pr
- sfcWind
- clt
- od440aer
- emidust
- od870aer
- clivi
- rsdscs
- abs550aer
- clwvi
- od550aer
- rsds
- prc
- evspsbl
