ERFs:
- atmabsSW
- ERFtsw
- ERFsurf
- atmabs
- ERFtlw
- DirectEff
- LWCloudEff
- ERFtcsaf
- ERFt
- LWDirectEff
- SWCloudEff
- CloudEff
- SWDirectEff
derived_vars:
- cdncvi
- concso4
- concoa
- conch2oaer
- concdust
vars:
- rsdscs
- prc
- clivi
- clt
- od550aer
- pr
- emidust
- abs550aer
- rsds
- od440aer
- clwvi
- od870aer
- sfcWind
- evspsbl
