ERFs:
- SWCloudEff
- atmabs
- SWDirectEff
- ERFt
- ERFtcsaf
- atmabsSW
- ERFsurf
- ERFtsw
- LWDirectEff
- ERFtlw
- DirectEff
- LWCloudEff
- CloudEff
derived_vars:
- concso4
- conch2oaer
- concdust
- cdncvi
- concoa
vars:
- abs550aer
- od440aer
- emidust
- sfcWind
- od550aer
- pr
- evspsbl
- clivi
- prc
- clwvi
- rsdscs
- od870aer
- clt
- rsds
