ERFs:
- ERFtsw
- atmabsSW
- atmabs
- ERFtlw
- ERFsurf
- ERFt
derived_vars:
- concso4
- concdust
- cdncvi
- concoa
vars:
- clt
- evspsbl
- clivi
- clwvi
- emidust
- prc
- od550aer
- rsds
- sfcWind
- pr
- rsdscs
- od870aer
- abs550aer
