ERFs:
- atmabs
- DirectEff
- ERFsurf
- CloudEff
- LWCloudEff
- atmabsSW
- SWCloudEff
- LWDirectEff
- SWDirectEff
- ERFtlw
- ERFtsw
- ERFt
- ERFtcsaf
derived_vars:
- conch2oaer
- concdust
- concoa
- concso4
vars:
- evspsbl
- clt
- od550aer
- rsds
- rsdscs
- abs550aer
- prc
- pr
- od440aer
- sfcWind
- emidust
- od870aer
- clwvi
- clivi
