ERFs:
- atmabsSW
- LWCloudEff
- atmabs
- ERFsurf
- ERFt
- ERFtcsaf
- SWCloudEff
- ERFtsw
- CloudEff
- DirectEff
- ERFtlw
- SWDirectEff
- LWDirectEff
derived_vars:
- conch2oaer
- concdust
- concso4
- concoa
vars:
- rsdscs
- clwvi
- rsds
- abs550aer
- clivi
- pr
- evspsbl
- sfcWind
- emidust
- prc
- od550aer
- clt
- od440aer
