ERFs:
- SWDirectEff
- ERFsurf
- ERFtlw
- CloudEff
- SWCloudEff
- LWDirectEff
- DirectEff
- ERFtsw
- atmabsSW
- LWCloudEff
- ERFtcsaf
- atmabs
- ERFt
derived_vars:
- concso4
- concoa
- cdncvi
- concdust
- conch2oaer
vars:
- abs550aer
- evspsbl
- od870aer
- rsds
- clwvi
- sfcWind
- clt
- od550aer
- rsdscs
- clivi
- pr
- prc
- emidust
- od440aer
