ERFs:
- atmabs
- atmabsSW
- ERFsurf
- ERFt
- ERFtsw
- ERFtcsaf
- ERFtlw
derived_vars:
- conch2oaer
- concdust
- concso4
- concoa
- cdncvi
vars:
- rsdscs
- clwvi
- od550aer
- rsds
- prc
- sfcWind
- abs550aer
- od440aer
- clivi
- od870aer
- emidust
- pr
- clt
- evspsbl
