import xarray as xr
from pyclim_noresm.aerosol_forcing import calc_direct_aerosol_radiative_effect
import copy
import time
VARS = snakemake.config['variables']

ERFt = xr.open_dataset(snakemake.input.ERFt)
ERFtaf = xr.open_dataset(snakemake.input.ERFtaf)

directEffect = calc_direct_aerosol_radiative_effect(ERFt[VARS[snakemake.wildcards.vName][0]],
                                    ERFtaf[VARS[snakemake.wildcards.vName][1]])

directEffect = directEffect.to_dataset(name=snakemake.wildcards.vName)
directEffect.attrs=copy.copy(ERFt.attrs)
directEffect['title']='Aerosol direct radiative effect'
directEffect['history'] = f'@{time.ctime()} Generated by: {__file__} ' + directEffect.attrs['history']
directEffect['source'] = ', '.join(snakemake.input) + ', ' + directEffect.attrs['source']
directEffect.to_netcdf(snakemake.output.outpath)