
# Root path to the CMIP archive
root_lustre: '/lustre/storeB/users/oveh/.synda/data/CMIP6'
root_noresm: '/home/oveh/mnt/NIRD_noresm/CMIP6'
root_noresmdev: '/home/oveh/mnt/NIRD_data/NorESM2_AerChemMIP_rerun_bugfix/CMIP6'

lustre: True

sources:
  - lustre
  - noresm

seperate_Noresm: True
# Set CMIP version
cmip_version: 'CMIP6'

activities:
  - 'AerChemMIP'
  - 'RFMIP'
#Regrid all models to common grid
regrid_params:
  dxdy:
    - 1.75
    - 2.00

# Set output format, can provide store output in aerocom naming convention
# By setting output format to aerocom
output_format: 'default'

# relative path to root directory of output 
# default = 'results'

out_dir : null
no_intermediate_files: False


# Default model variant used nothing else is specified
variant_default: 'r1i1p1f1'

model_specific_variant:
  piClim-control:
    UKESM1-0-LL : 'r1i1p1f4'
    GISS-E2-1-G : 'r1i1p3f1'
    CNRM-ESM2-1 : 'r1i1p1f2'
    MIROC6 : 'r11i1p1f1'
    NorESM2-LM : 'r1i1p2f1'
    NorESM2.0.6dev-LM: 'r1i1p3f1'
  piClim-2xdust:
    UKESM1-0-LL : 'r1i1p1f4'
    GISS-E2-1-G : 'r1i1p3f1'
    CNRM-ESM2-1 : 'r1i1p1f2'
    NorESM2-LM : 'r1i1p2f1'
    NorESM2.0.6dev-LM: 'r1i1p3f1'

experiments:
  control:
    - 'piClim-control'
  experiments:
    - 'piClim-2xdust'
    - 'abrupt-4xCO2'
    - 'piControl'
    - 'piClim-aer'
    - 'histSST'
    - 'hist-piAer'
    - 'histSST-piAer'
    - 'historical'
    - 'hist-noLu'
    - 'piClim-2xss'
    - 'piClim-2xDMS'
    - 'piClim-lu'
    - 'piClim-CH4'
    - 'piClim-NTCF'
    - 'piClim-BC'
    - 'piClim-SO2'
    - 'piClim-OC'


# Default table_id
table_id_default: 'Amon' 

# Variables that not in default table_id: (default is Amon)
use_derived_vars:
  loaddust: True

table_ids:
  rlutaf: 'AERmon'
  rsutcsaf: 'AERmon'
  rsutaf: 'AERmon'
  rlutcsaf: 'AERmon'
  emidust: 'AERmon'
  od550dust: 'AERmon'
  od550aer: 'AERmon'
  od550csaer: 'AERmon'
  od550lt1aer: 'AERmon'
  lwp: 'AERmon'
  cdnc: 'AERmon'
  mmrdust: 'AERmon'
  od550bb: 'AERmon'
  airmass: 'AERmon'
  mmrss: 'AERmon'
  mmrsoa: 'AERmon'
  mmroa:  'AERmon'
  mmrbc: 'AERmon'
  mmrso4: 'AERmon'
  loaddust: 'AERmon'
  concdust: 'AERmon'
  ccn: 'AERmon'
  abs550aer: 'AERmon'


variables: 
  ERFt: ['rsut', 'rsdt','rlut']
  ERFtcs: ['rsutcs','rsdt','rlutcs']
  ERFtaf: ['rsutaf','rsdt','rlutaf']
  ERFtcsaf: ['rsutcsaf','rsdt','rlutcsaf']
  ERFtsw: ['rsut','rsdt']
  ERFtswaf: ['rsutaf', 'rsdt']  
  ERFtswcsaf: ['rsutcsaf','rsdt']
  ERFtlw: ['rlut']
  ERFtlwaf: ['rlutaf']
  ERFtlwcs: ['rlutcs']
  ERFtlwcsaf : ['rlutcsaf']
  ERFsurfsw: ['rsus','rsds']
  ERFsurflw: ['rlus', 'rlds']
  ERFsurfswcs: ['rsuscs', 'rsdscs']
  ERFtswcs: ['rsutcs', 'rsdt']
  ERFsurf: ['rsus', 'rsds', 'rlus', 'rlds']
  ERFsurfcs: ['rsuscs','rsdscs', 'rsutcs','rlus']
  DirectEff: ['ERFt', 'ERFtaf']
  SWDirectEff: ['ERFtsw','ERFtswaf']
  SWDirectEff_cs: ['ERFtswcs','ERFtswcsaf']
  LWDirectEff: ['ERFtlw','ERFtlwaf']
  LWDirectEff_cs: ['ERFtlwcs','ERFtlwcsaf']
  CloudEff: ['ERFtaf','ERFtcsaf']
  SWCloudEff : ['ERFtswaf','ERFtswcsaf']
  LWCloudEff : ['ERFtlwaf','ERFtlwcsaf']
  atmabsSW: ['ERFtsw','ERFsurfsw']
  atmabs: ['ERFt','ERFsurf']
  atmabsLW: ['ERFtlw','ERFsurflw']


burdens_dict:
  concdust: 'mmrdust'
  concpm1: 'mmrpm1'
  concpm10: 'mmrpm10'
  concpm2p5: 'mmrpm2p5'
  concso4: 'mmrso4'
  concss: 'mmrss'
  concsoa: 'mmrsoa'
  concoa: 'mmroa'
  conch2oaer: 'mmraerh2o'

# These variables will be accumulated when resampled e.g. from Amon to Ayear
accumalative_vars:
  - emidust
  - depdust
  - concdust
  - loaddust

# Define the pressurelevels for low, middle and high clouds hPa: 
cloud_def:
  low: 
    bottom: 1000
    top: 700
  middle:
    bottom: 700
    top: 400
  high:
    bottom: 400
    top: null

cloud_def_height:
  low: 
    bottom: 0
    top: 3000
  middle:
    bottom: 3000
    top: 6000
  high:
    bottom: 6000
    top: null

variable_scalings:
  clivi:
    c : 1000
    units : 'g m-2'
  clwvi:
    c : 1000
    units: 'g m-2'
  cli:
    c : 1000
    units : 'g g-1'  
  cdnc:
    c : 0.0000001
    units: '# cm-3'
  mmrdust:
    c : 1000
    units : 'g g-1' 
