
# Root path to the CMIP archive
root_nird : '/nird/datalake/NS9560K/ESGF/CMIP6'
root_lustre: '/lustre/storeB/users/oveh/.synda/data/CMIP6'
root_noresm: '/projects/NS9034K/CMIP6'
root_noresmdev: '/home/oveh/mnt/NIRD_data/NorESM2_AerChemMIP_rerun_bugfix/CMIP6'

lustre: False

sources:
  - nird
  - noresm

seperate_Noresm: True
# Set CMIP version
cmip_version: 'CMIP6'

activities:
  - 'AerChemMIP'
  - 'RFMIP'
  - 'CMIP'
#Regrid all models to common grid
regrid_params:
  dxdy:
    - 1.75
    - 2.00

# Set output format, can provide store output in aerocom naming convention
# By setting output format to aerocom
output_format: 'default'

# relative path to root directory of output 
# default = 'results'

out_dir : null
no_intermediate_files: False

time_slice:
  start: 2
  end: null

out_dir: '/datalake/NS2345K/ovewh/results/'

# Default model variant used nothing else is specified
variant_default: 'r1i1p1f1'

model_specific_variant:
  piClim-control:
    UKESM1-0-LL : 'r1i1p1f4'
    GISS-E2-1-G : 'r1i1p3f1'
    CNRM-ESM2-1 : 'r1i1p1f2'
    MIROC6 : 'r11i1p1f1'
    NorESM2-LM : 'r1i1p2f1'
    NorESM2.0.6dev-LM: 'r1i1p3f1'
  piClim-2xdust:
    UKESM1-0-LL : 'r1i1p1f4'
    GISS-E2-1-G : 'r1i1p3f1'
    CNRM-ESM2-1 : 'r1i1p1f2'
    NorESM2-LM : 'r1i1p2f1'
    NorESM2.0.6dev-LM: 'r1i1p3f1'

experiments:
  control:
    - 'piClim-control'
  experiments:
    - 'piClim-2xdust'
    - 'abrupt-4xCO2'
    - 'piControl'
    - 'piClim-aer'
    - 'histSST'
    - 'hist-piAer'
    - 'histSST-piAer'
    - 'historical'
    - 'hist-noLu'
    - 'piClim-2xss'
    - 'piClim-2xDMS'
    - 'piClim-lu'
    - 'piClim-CH4'
    - 'piClim-NTCF'
    - 'piClim-BC'
    - 'piClim-SO2'
    - 'piClim-OC'


# Default table_id
table_id_default: 'Amon' 


use_derived_vars:
  loaddust: 
    all: True
  rlutaf: 
    IPSL-CM6A-LR-INCA: True
    all: False


# Variables that not in default table_id: (default is Amon)
table_ids:
  ta: ['CFmon','Amon']
  rlutaf: 'AERmon'
  rsutcsaf: 'AERmon'
  rsutaf: 'AERmon'
  rlutcsaf: 'AERmon'
  emidust: 'AERmon'
  od550dust: 'AERmon'
  od550aer: 'AERmon'
  od550csaer: 'AERmon'
  od550lt1aer: 'AERmon'
  lwp: 'AERmon'
  cdnc: 'AERmon'
  mmrdust: 'AERmon'
  od550bb: 'AERmon'
  airmass: 'AERmon'
  mmrss: 'AERmon'
  mmrsoa: 'AERmon'
  mmroa:  'AERmon'
  mmrbc: 'AERmon'
  mmrso4: 'AERmon'
  loaddust: 'AERmon'
  concdust: 'AERmon'
  ccn: 'AERmon'
  o3: 'AERmon'
  abs550aer: 'AERmon'
  mmrnh4: 'AERmon'
  mmrno3: 'AERmon'

variables: 
  ERFt: ['rsut', 'rsdt','rlut']
  ERFtcs: ['rsutcs','rsdt','rlutcs']
  ERFtaf: ['rsutaf','rsdt','rlutaf']
  ERFtcsaf: ['rsutcsaf','rsdt','rlutcsaf']
  ERFtsw: ['rsut','rsdt']
  ERFtswaf: ['rsutaf', 'rsdt']  
  ERFtswcsaf: ['rsutcsaf','rsdt']
  ERFtlw: ['rlut']
  ERFtlwaf: ['rlutaf']
  ERFtlwcs: ['rlutcs']
  ERFtlwcsaf : ['rlutcsaf']
  ERFsurfsw: ['rsus','rsds']
  ERFsurflw: ['rlus', 'rlds']
  ERFsurfswcs: ['rsuscs', 'rsdscs']
  ERFtswcs: ['rsutcs', 'rsdt']
  ERFsurf: ['rsus', 'rsds', 'rlus', 'rlds']
  ERFsurfcs: ['rsuscs','rsdscs', 'rsutcs','rlus']
  DirectEff: ['ERFt', 'ERFtaf']
  SWDirectEff: ['ERFtsw','ERFtswaf']
  SWDirectEff_cs: ['ERFtswcs','ERFtswcsaf']
  LWDirectEff: ['ERFtlw','ERFtlwaf']
  LWDirectEff_cs: ['ERFtlwcs','ERFtlwcsaf']
  CloudEff: ['ERFtaf','ERFtcsaf']
  SWCloudEff : ['ERFtswaf','ERFtswcsaf']
  LWCloudEff : ['ERFtlwaf','ERFtlwcsaf']
  atmabsSW: ['ERFtsw','ERFsurfsw']
  atmabs: ['ERFt','ERFsurf']
  atmabsLW: ['ERFtlw','ERFsurflw']


burdens_dict:
  concbc: 'mmrbc'
  concdust: 'mmrdust'
  concpm1: 'mmrpm1'
  concpm10: 'mmrpm10'
  concpm2p5: 'mmrpm2p5'
  concso4: 'mmrso4'
  concss: 'mmrss'
  concsoa: 'mmrsoa'
  concoa: 'mmroa'
  conch2oaer: 'mmraerh2o'
  concnh4 : mmrnh4
  conco3: 'o3'
  concno3: mmrno3

# These variables will be accumulated when resampled e.g. from Amon to Ayear
accumalative_vars:
  - emidust
  - depdust
  - concdust
  - loaddust

# Define the pressurelevels for low, middle and high clouds hPa: 
cloud_def:
  low: 
    bottom: 1000
    top: 700
  middle:
    bottom: 700
    top: 400
  high:
    bottom: 400
    top: 50

cloud_def_height:
  low: 
    bottom: 0
    top: 3000
  middle:
    bottom: 3000
    top: 6000
  high:
    bottom: 6000
    top: null

variable_scalings:
  clivi:
    c : 1000
    units : 'g m-2'
  clwvi:
    c : 1000
    units: 'g m-2'
  cli:
    c : 1000
    units : 'g g-1'  
  cdnc:
    c : 0.0000001
    units: '# cm-3'
  mmrdust:
    c : 1000
    units : 'g g-1' 


# Define dust source regions:

dust_source_regions:
  Western north Africa:
    latmin: 18
    latmax: 37.5
    lonmin: -20
    lonmax: 7.5
  Eastern north Africa:
    latmin: 18
    latmax: 37.5
    lonmin: 7.5
    lonmax: 35
  Sahel:
    latmin: 0
    latmax: 18
    lonmin: -20
    lonmax: 35
  Middle east:
    latmin: 0
    latmax: 35
    lonmin: 35
    lonmax: 75
  Central Asia:
    latmin: 35
    latmax: 50
    lonmin: 35
    lonmax: 70
  Southern Africa:
    latmin: -40
    latmax: 0
    lonmin: 0
    lonmax: 40
  East Asia:
    latmin: 35
    latmax: 50
    lonmin: 70
    lonmax: 120
  North America:
    latmin: 20
    latmax: 45
    lonmin: -130
    lonmax: -80
  Australia:
    latmin: -40
    latmax: -10
    lonmin: 110
    lonmax: 160
  South America:
    latmin: -60
    latmax: 0
    lonmin: -80
    lonmax: -20


# Dust interest regions

dust_interest_regions:
  North Atlantic:
    latmin: -6
    latmax: 34
    lonmin: -66
    lonmax: -16
  North Africa:
    latmin: 1
    latmax: 36
    lonmin: -16
    lonmax: 37
  Middle East and Central Asia:
    latmin: 19
    latmax: 44
    lonmin: 37
    lonmax: 79
  Arabian Sea:
    latmin: -6
    latmax: 19
    lonmin: 42
    lonmax: 82
  East Asia:
    latmin: 23
    latmax: 61
    lonmin: 79
    lonmax: 117
  North Pacific:
    latmin: 15
    latmax: 48
    lonmin: 117
    lonmax: 147