
# Root path to the CMIP archive
root: '/cluster/shared/ESGF'
# Set CMIP version
cmip_version: 'CMIP6'
# Define under which CMIP6 ativities to search under

# Define the experiments to consider
experiments: ['piClim-2xdust','piClim-control']

variant_default: 'r1i1p1f1'

model_specific_variant:
  UKESM1-0-LL : 'r1i1p1f4'

# If prefered version is not latest or latest does not exist?
version:
  MPI-ESM-1-2-HAM: 'v20190628'

variables: 
  ERFt: ['rsut', 'rsdt','rlut']
  ERFtcs: ['rsutcs','rsdt','rlutcs']
  ERFtsw: ['rsut','rsdt']
  ERFsurfsw: ['rsus','rsds']
  ERFsurfswcs: ['rsuscs', 'rsdscs']
  ERFtswcs: ['rsutcs', 'rsdt']
  ERFsurf: ['rsus', 'rsds', 'rlus', 'rlds']
  ERFsurfcs: ['rsuscs','rsdscs', 'rsutcs','rlus']
  atmabsSW: ['ERFtsw','ERFsurfsw']
  atmabs: ['ERFt','ERFsurf']


