
# Root path to the CMIP archive
root: '/cluster/shared/ESGF'
# Set CMIP version
cmip_version: 'CMIP6'

# Default model variant used nothing else is specified
variant_default: 'r1i1p1f1'

model_specific_variant:
  control:
    UKESM1-0-LL : 'r1i1p1f4'
    GISS-E2-1-G : 'r1i1p3f1'
    CNRM-ESM2-1 : 'r1i1p1f2'
    MIROC6 : 'r11i1p1f1'
  experiment:
    UKESM1-0-LL : 'r1i1p1f4'
    GISS-E2-1-G : 'r1i1p3f1'
    CNRM-ESM2-1 : 'r1i1p1f2'



experiments:
  - 'piClim-control'
  - 'piClim-2xdust'

# If prefered version is not latest or latest does not exist?
version:
  version_control:
    MPI-ESM-1-2-HAM: 'v20190628'
  version_exp:
    MPI-ESM-1-2-HAM: 'latest'

# Default table_id
table_id_default: 'Amon' 

# Variables that not in default table_id: (default is Amon)
table_ids:
  rlutaf: 'AERmon'
  rsutcsaf: 'AERmon'
  rsutaf: 'AERmon'
  rlutcsaf: 'AERmon'


variables: 
  ERFt: ['rsut', 'rsdt','rlut']
  ERFtcs: ['rsutcs','rsdt','rlutcs']
  ERFtaf: ['rsutaf','rsdt','rlutaf']
  ERFtcsaf: ['rsutcsaf','rsdt','rlutcsaf']
  ERFtsw: ['rsut','rsdt']
  ERFtswaf: ['rsutaf', 'rsdt']
  ERFtswcsaf: ['rsutcsaf','rsdt']
  ERFtlw: ['rlut']
  ERFtlwaf: ['rlutaf']
  ERFtlwcs: ['rlutcs']
  ERFtlwcsaf : ['rlutcsaf']
  ERFsurfsw: ['rsus','rsds']
  ERFsurfswcs: ['rsuscs', 'rsdscs']
  ERFtswcs: ['rsutcs', 'rsdt']
  ERFsurf: ['rsus', 'rsds', 'rlus', 'rlds']
  ERFsurfcs: ['rsuscs','rsdscs', 'rsutcs','rlus']
  SWDirectEff: ['ERFtsw','ERFtswaf']
  SWDirectEff_cs: ['ERFtswcs','ERFtswcsaf']
  LWDirectEff: ['ERFtlw','ERFtlwaf']
  LWDirectEff_cs: ['ERFtlwcs','ERFtlwcsaf']
  CloudEff: ['ERFtaf','ERFtcsaf']
  SWCloudEff : ['ERFtswaf','ERFtswcsaf']
  LWCloudEff : ['ERFtlwaf','ERFtlwcsaf']
  atmabsSW: ['ERFtsw','ERFsurfsw']
  atmabs: ['ERFt','ERFsurf']



lookup_file_endings: 'config/lookup_file_endings.yaml'
