ACCESS-CM2: CSIRO-ARCCSS
ACCESS-ESM1-5: CSIRO
AWI-CM-1-1-MR: AWI
AWI-ESM-1-1-LR: AWI
BCC-CSM2-MR: BCC
BCC-ESM1: BCC
CAMS-CSM1-0: CAMS
CAS-ESM2-0: CAS
CESM2: NCAR
CESM2-FV2: NCAR
CESM2-WACCM: NCAR
CESM2-WACCM-FV2: NCAR
CIESM: THU
CMCC-CM2-HR4: CMCC
CMCC-CM2-SR5: CMCC
CMCC-CM2-VHR4: CMCC
CMCC-ESM2: CMCC
CNRM-CM6-1: CNRM-CERFACS
CNRM-CM6-1-HR: CNRM-CERFACS
CNRM-ESM2-1: CNRM-CERFACS
CanESM5: CCCma
CanESM5-CanOE: CCCma
E3SM-1-0: E3SM-Project
E3SM-1-1: E3SM-Project
E3SM-1-1-ECA: E3SM-Project
EC-Earth3: EC-Earth-Consortium
EC-Earth3-AerChem: EC-Earth-Consortium
EC-Earth3-CC: EC-Earth-Consortium
EC-Earth3-LR: EC-Earth-Consortium
EC-Earth3-Veg: EC-Earth-Consortium
EC-Earth3-Veg-LR: EC-Earth-Consortium
EC-Earth3P: EC-Earth-Consortium
EC-Earth3P-HR: EC-Earth-Consortium
FGOALS-f3-L: CAS
FGOALS-g3: CAS
FIO-ESM-2-0: FIO-QLNM
GFDL-AM4: NOAA-GFDL
GFDL-CM4: NOAA-GFDL
GFDL-ESM4: NOAA-GFDL
GISS-E2-1-G: NASA-GISS
GISS-E2-1-G-CC: NASA-GISS
GISS-E2-1-H: NASA-GISS
GISS-E2-2-G: NASA-GISS
GISS-E2-2-H: NASA-GISS
HadGEM3-GC31-HH: NERC
HadGEM3-GC31-HM: MOHC
HadGEM3-GC31-LL: MOHC
HadGEM3-GC31-MM: MOHC
ICON-ESM-LR: MPI-M
IITM-ESM: CCCR-IITM
INM-CM4-8: INM
INM-CM5-0: INM
IPSL: PMIP
IPSL-CM5A2-INCA: IPSL
IPSL-CM6A-LR: IPSL
IPSL-CM6A-LR-INCA: IPSL
KACE-1-0-G: NIMS-KMA
KIOST-ESM: KIOST
MCM-UA-1-0: UA
MIROC-ES2L: MIROC
MIROC6: MIROC
MPI-ESM-1-2-HAM: HAMMOZ-Consortium
MPI-ESM1-2-HR: MPI-M
MPI-ESM1-2-LR: MPI-M
MPI-M: PMIP
MRI: PMIP
MRI-ESM2-0: MRI
NESM3: NUIST
NUIST: PMIP
NorCPM1: NCC
NorESM2-LM: NCC
NorESM2-MM: NCC
SAM0-UNICON: SNU
TaiESM1: AS-RCEC
UKESM1-0-LL: MOHC
