1pctCO2: CMIP
1pctCO2-bgc: C4MIP
1pctCO2-cdr: CDRMIP
1pctCO2-cdr-bgc: C4MIP
G6solar: GeoMIP
G6sulfur: GeoMIP
IPSL-CM6A-LR: PMIP
MPI-ESM1-2-LR: PMIP
MRI-ESM2-0: PMIP
NESM3: PMIP
abrupt-0p5xCO2: CFMIP
abrupt-2xCO2: CFMIP
abrupt-4xCO2: CMIP
abrupt-solm4p: CFMIP
abrupt-solp4p: CFMIP
amip: CMIP
dcppA-assim: DCPP
esm-1pct-brch-1000PgC: C4MIP
esm-hist: CMIP
esm-pi-CO2pulse: CDRMIP
esm-pi-cdr-pulse: CDRMIP
esm-piControl: CMIP
esm-piControl-spinup: CMIP
esm-ssp585: C4MIP
faf-all: FAFMIP
faf-heat: FAFMIP
faf-heat-NA50pct: FAFMIP
faf-passiveheat: FAFMIP
faf-stress: FAFMIP
faf-water: FAFMIP
highres-future: HighResMIP
hist-1950: HighResMIP
hist-CO2: DAMIP
hist-GHG: DAMIP
hist-aer: DAMIP
hist-bgc: C4MIP
hist-nat: DAMIP
hist-noLu: LUMIP
hist-piAer: AerChemMIP
hist-piNTCF: AerChemMIP
hist-resIPO: GMMIP
hist-sol: DAMIP
hist-spAer-all: RFMIP
hist-stratO3: DAMIP
hist-volc: DAMIP
histSST: AerChemMIP
histSST-piAer: AerChemMIP
histSST-piNTCF: AerChemMIP
historical: CMIP
jangtest: AerChemMIP
lgm: PMIP
lig127k: PMIP
midHolocene: PMIP
midPliocene-eoi400: PMIP
omip1: OMIP
omip2: OMIP
past1000: PMIP
piClim-2xDMS: AerChemMIP
piClim-2xVOC: AerChemMIP
piClim-2xdust: AerChemMIP
piClim-2xfire: AerChemMIP
piClim-2xss: AerChemMIP
piClim-4xCO2: RFMIP
piClim-BC: AerChemMIP
piClim-NTCF: AerChemMIP
piClim-OC: AerChemMIP
piClim-SO2: AerChemMIP
piClim-VOC: AerChemMIP
piClim-aer: RFMIP
piClim-anthro: RFMIP
piClim-control: RFMIP
piClim-ghg: RFMIP
piClim-histaer: RFMIP
piClim-histall: RFMIP
piClim-histghg: RFMIP
piClim-histnat: RFMIP
piClim-lu: RFMIP
piControl: CMIP
piControl-spinup: CMIP
ssp119: ScenarioMIP
ssp126: ScenarioMIP
ssp126-ssp370Lu: LUMIP
ssp245: ScenarioMIP
ssp245-GHG: DAMIP
ssp245-aer: DAMIP
ssp245-nat: DAMIP
ssp245-stratO3: DAMIP
ssp370: ScenarioMIP
ssp370-lowNTCF: AerChemMIP
ssp434: ScenarioMIP
ssp460: ScenarioMIP
ssp534-over: ScenarioMIP
ssp534-over-bgc: C4MIP
ssp585: ScenarioMIP
ssp585-bgc: C4MIP
