configfile: 'config/config.yaml'

include: 'rules/compute_ERF.smk'

wildcard_constraints:
    activities='|'.join(config['activities']),
    experiments='|'.join(config['experiments'])

ACTIVITIES=config['activities']
ROOT_PATH = config['root']
CMIP_VER = config['cmip_version']

VARS = config['variables']