import os
import glob

configfile: 'config/config.yaml'

ACTIVITIES=config['activities']
ROOT_PATH = config['root']
CMIP_VER = config['cmip_version']
VARS=config['variables']

# Definition of the variables used for when calculating the
# different forcings.
include: 'rules/compute_ERF.smk'

wildcard_constraints:
    activities='|'.join(config['activities']),
    experiments='|'.join(config['experiments'])
